# Generated by Django 4.2.13 on 2024-08-05 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_user_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='images')),
                ('logo', models.ImageField(upload_to='images')),
                ('homepage_cell_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_cell_1', to='main_site.service')),
                ('homepage_cell_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_cell_2', to='main_site.service')),
                ('homepage_cell_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_cell_3', to='main_site.service')),
                ('homepage_cell_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_cell_4', to='main_site.service')),
                ('homepage_cell_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_cell_5', to='main_site.service')),
                ('homepage_cell_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_cell_6', to='main_site.service')),
            ],
        ),
    ]
