# Generated by Django 4.2.13 on 2024-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_product_alter_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_notificated',
            field=models.BooleanField(default=False, verbose_name='Пользователь уведомлен о записи'),
        ),
    ]
