# Generated by Django 4.2.13 on 2024-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('worker', 'service', 'date'), name='unique_worker_service_date'),
        ),
        migrations.AddConstraint(
            model_name='scheduleperiod',
            constraint=models.UniqueConstraint(fields=('schedule', 'date_time_start'), name='unique_schedule_period'),
        ),
    ]
