# Generated by Django 4.2.13 on 2024-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_schedule_unique_worker_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_hotificate_user',
            field=models.BooleanField(default=False, verbose_name='Админ напомнил о записи'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_notificated',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено'),
        ),
    ]
