# Generated by Django 4.2.13 on 2024-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_appointment_admin_hotificate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность сотрудника (Вводится в ручную)'),
        ),
    ]
